import type { Metadata } from 'next';

import Navbar from '@/components/navbar/Navbar';

import styles from './layout.module.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AuthenticatedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={styles.layoutContainer}>
      <Navbar />
      {children}
    </div>
  );
}
