import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

import { Providers } from './providers';

import './globals.scss';
import { getUser } from '@/controllers/User';

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={poppins.className}>
        <Providers>
          {children}
          <p>{user.email}</p>
        </Providers>
      </body>
    </html>
  );
}
